### ISSUE TITLE
Getting this error when importing ffn, I am working with Python 3.7, thanks

### ISSUE THREAD

**Issue by P4k0p4N** [pmorissette/ffn#108]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-8c56737ca326> in <module>
     16 from ipywidgets import interact, interactive,fixed, interact_manual
     17 import ipywidgets as widgets
---> 18 import ffn

~/anaconda3/envs/DSPy/lib/python3.7/site-packages/ffn/__init__.py in <module>
----> 1 from . import core
      2 from . import data
      3 
      4 from .data import get
      5 #from .core import year_frac, PerformanceStats, GroupStats, merge

~/anaconda3/envs/DSPy/lib/python3.7/site-packages/ffn/core.py in <module>
     25 
     26 if 'DISPLAY' not in os.environ:
---> 27     matplotlib.use('agg', warn=False)
     28 
     29 from matplotlib import pyplot as plt  # noqa

TypeError: use() got an unexpected keyword argument 'warn'

**Comment by timkpaine** [comment]
downgrade to matplotlib <3. This was fixed in https://github.com/pmorissette/ffn/pull/104, will be fixed in the next release
